name: Prueba de Automatizacion

on:
  push:
    branches:
      - main

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Validar consola
        run: echo "Hola, esta es una prueba de automatizacion en GitHub Actions"